### PR TITLE
Display rendering timings

### PR DESCRIPTION
**Pull request by SteveSandersonMS**
Provides a fuller end-to-end picture of the timings between the form submission and the data being on screen.

### CODE REVIEW

**Comment by SteveSandersonMS** [comment]
The reason I suggest removing virtualization is just to show the underlying raw rendering perf. I agree that in scenarios like this one, virtualization is desirable for real apps, but in this benchmark it makes rendering too fast to measure :)

Here it is without virtualization:

image

... and here's the same with virtualization:

image

**Comment by JamesNK** [comment]
I like measuring render time, but I'd like to have a checkbox to enable/disable virtualization. It makes isolating the impact of serialization easier. It's also a good advertisement for the benefits of using virtualization when attacking render time problems.

One problem would be an explosion of databinding duplication in the Razor page:

* grpc without virt
* grpc with virt
* rest without virt
* rest with virt

Could reduce duplication by having the gRPC DTO and REST DTO implement an interface and databind that.

**Comment by SteveSandersonMS** [comment]
@JamesNK Totally up to you. I just wanted to get some concrete numbers on rendering to be able to make sense of the discussion about that. I don't mind if you choose not to merge this 😄

**Comment by JamesNK** [comment]
Cool beans. I’ll look at it tomorrow. More chances for me to learn Blazor

**Comment by SteveSandersonMS** [comment]
OK it made me interested in how it would look to factor the UI so it can be toggled between virtualized or not, so I've added a further commit that does it without increasing the amount of duplication.

**Pull request merged**
